// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgaMlvQvoEcos8araWZR--YpBZ-i2cTI',
    appId: '1:202223024438:web:0f32805ceaf5dee5c45b97',
    messagingSenderId: '202223024438',
    projectId: 'luclub-f168c',
    authDomain: 'luclub-f168c.firebaseapp.com',
    storageBucket: 'luclub-f168c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC96VB4lYLBCkoLf3eFsxNS0junYonjwEc',
    appId: '1:202223024438:android:c3487c2f9e2357dcc45b97',
    messagingSenderId: '202223024438',
    projectId: 'luclub-f168c',
    storageBucket: 'luclub-f168c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC37wM4nWLaCeIsAs3b1wrdMq61-MXfJaY',
    appId: '1:202223024438:ios:2fca9e354f44b250c45b97',
    messagingSenderId: '202223024438',
    projectId: 'luclub-f168c',
    storageBucket: 'luclub-f168c.appspot.com',
    iosClientId: '202223024438-ppo5bboismou3ghnka369nkihi3es32n.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC37wM4nWLaCeIsAs3b1wrdMq61-MXfJaY',
    appId: '1:202223024438:ios:2fca9e354f44b250c45b97',
    messagingSenderId: '202223024438',
    projectId: 'luclub-f168c',
    storageBucket: 'luclub-f168c.appspot.com',
    iosClientId: '202223024438-ppo5bboismou3ghnka369nkihi3es32n.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubManagementFlutter',
  );
}
